x-SManager:
  side_menu:
    - Ссылки:
        SHM web: http://${ODS_SM_SERVER_IP}:${EXT_PORT}
  ui_edit_vars:
    Порт веб интерфейса: EXT_PORT
    TimeZone: TZ
  source:
    branch: smanager-params
    url: https://github.com/SManager-forks/shm.git
    yaml_path: https://raw.githubusercontent.com/SManager-forks/shm/smanager-params/docker-compose.yml
    readme_path: https://raw.githubusercontent.com/SManager-forks/shm/smanager-params/README.md

version: '2.1'
services:
  api:
    image: "danuk/shm-api:0.1"
    restart: always
    links:
      - core
  core:
    image: "danuk/shm-core:0.1"
    restart: always
    environment:
      TZ: ${TZ}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${ODS_SM_GENERATE_RANDOM_UserPASS_20}
      DB_HOST: mysql
      DB_PORT: 3306
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
  spool:
    image: "danuk/shm-core:0.1"
    restart: always
    environment:
      TZ: ${TZ}
      SHM_ROLE: "spool"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${ODS_SM_GENERATE_RANDOM_UserPASS_20}
      DB_HOST: mysql
      DB_PORT: 3306
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
  admin:
    image: "danuk/shm-admin:0.1"
    restart: always
    environment:
      SHM_URL: http://api
    ports:
      - "${EXT_PORT}:80"
    links:
      - api
  client:
    image: "danuk/shm-client:0.1"
    restart: always
    environment:
      SHM_URL: http://api
    ports:
      - "8082:80"
    links:
      - api
  mysql:
    image: "mysql:8.0"
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${ODS_SM_GENERATE_RANDOM_RootPASS_20}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${ODS_SM_GENERATE_RANDOM_UserPASS_20}
    volumes:
      - "./mysql-data:/var/lib/mysql"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 3s
      retries: 10

# volumes:
#   mysql-data:
#     driver: local

